config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :games, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
    # resources :jenres, only: [:index, :create, :edit, :update]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    # get '/about' => 'homes#about',as: 'about'
    # resources :games, only: [:new, :create]
    get 'games/search' => "games#search"
    resources :games, only: %i[show], params: :item_code
    # get 'games' => 'games#index'
    get 'games/:id' => 'games#show',as: 'games/show'



    get 'current_customer/show' => 'customers#show'
    get 'current_customer/information/edit' => 'customers#edit'
    patch 'current_customer/show' => "customers#update"
    put 'current_customer/show' => "customers#update"
    get 'current_customer/unsubscribe' => 'customers#unsubscribe',as: 'unsubscribe'
    patch 'current_customer/withdrawal' => 'customers#withdrawal',as: 'withdrawal'

    # get 'posts/new' => 'posts#new'
    # post 'posts' => 'posts#create'
    # get 'posts' => 'posts#index'
    # get 'posts/:id' => 'posts#show',as: 'posts/show'
    get "search" => "posts#search"

    resources :posts, only: [:new, :create, :index, :show, :edit, :update] do
      resources :comments, only: [:create]
    end



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_post_and_tag.rb
class AssociationPostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :customer

  validates :comment_content, presence: true
end

app/models/comment_notification.rb
class CommentNotification < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :date_of_birth, presence: true


  def self.guest_sign_in
    pp '--------------------------'
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "ユーザー"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
      user.nickname = "ゲストユーザー"
      user.date_of_birth = "2023/08/05"
      user.gender = 2

    end
  end

  enum gender: { man: 0, woman: 1, guest: 2 }

end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/follow_notification.rb
class FollowNotification < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  # belongs_to :jenre, optional: true
  has_many :posts, dependent: :destroy
end

app/models/jenre.rb
class Jenre < ApplicationRecord
  has_many :game, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :game
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags


  validates :body, presence: true
  validates :star, presence: true

  # scope :published, -> {where(is_published_flag: true)}
  # scope :unpublished, -> {where(is_published_flag: false)}

  enum status: { public: 0, private: 1 }, _prefix: true

  def self.search(keyword)
    where("facility_name LIKE ? or address LIKE ? or detailed_description LIKE ?", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%")
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :association_post_and_tags, dependent: :destroy
  has_many :posts, through: :association_post_and_tags

  validates :tag_type, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)

  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page])
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "新しいタグを追加しました。"
    else
      @tags = Tag.page(params[:page])
      flash.now[:alert] = "タグの追加に失敗しました。"
      render :index
    end
  end


  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの更新に成功しました。"
    else
      flash.now[:alert] = "タグの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_type, tag_ids: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/jenres_helper.rb
module Admin::JenresHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h5><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h5>
  </div><br />

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
      <p>氏名</p>
      <p class="pt-1">フリガナ</p>
      <p class="pt-2">ニックネーム</p>
      <p class="pt-2">生年月日</p>
      <p class="pt-2">性別</p>
      <p class="pt-2">メールアドレス</p>
      <p class="pt-2">会員ステータス</p>
    </div>

    <div class="col-8">
      <%= form_with model: @customer, url: admin_customer_path do |f| %>
        <p><%= @customer.id %></p>
        <p><%= f.text_field :last_name %><span class="ml-5"><%= f.text_field :first_name %></span></p>
        <p><%= f.text_field :last_name_kana %><span class="ml-5"><%= f.text_field :first_name_kana %></span></p>
        <p><%= f.text_field :nickname %></p>
        <p><%= f.text_field :date_of_birth %></p>
        <p><%= f.text_field :gender %></p>
        <p><%= f.email_field :email %></p>
        <% if @customer.is_deleted == false %>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
            <label class="form-check-label" for="exampleRadios1">
              有効
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
            <label class="form-check-label" for="exampleRadios2">
              退会
            </label>
          </div>
        <% else %>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1">
            <label class="form-check-label" for="exampleRadios1">
              有効
            </label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2" checked>
            <label class="form-check-label" for="exampleRadios2">
              退会
            </label>
          </div>
        <% end %>

        <p class="mt-5"><%= f.submit "変更を保存", class: "btn btn-lg btn-success" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">

  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-8">
      <h5 class="mb-3">会員一覧</h5>
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <th><%= customer.id %></th>
              <th><%= link_to  customer.last_name + customer.first_name, admin_customer_path(customer.id) %></th>
              <th><%= customer.email %></th>
              <th>
                <% if customer.is_deleted == false %>
                  <p class="text-success">有効</p>
                <% else %>
                  <p class="text-muted">退会</p>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="d-flex justify-content-center">
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h5><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h5>
  </div><br />

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
      <p>氏名</p>
      <p>フリガナ</p>
      <p>ニックネーム</p>
      <p>生年月日</p>
      <p>性別</p>
      <p>メールアドレス</p>
      <p>会員ステータス</p>
    </div>
    <div class="col-8">
      <p><%= @customer.id %></P>
      <p><%= @customer.last_name + @customer.first_name %></p>
      <p><%= @customer.last_name_kana + @customer.first_name_kana %></p>
      <p><%= @customer.nickname %></p>
      <p><%= @customer.date_of_birth %></p>
      <p><%= @customer.gender_i18n %></p>
      <p><%= @customer.email %></p>
      <% if @customer.is_deleted == false %>
        <p class="text-success">有効</p>
      <% else %>
        <p class="text-muted">退会</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-9 d-flex flex-row bd-highlight mb-3">
      <p><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></p><span>　　　　</span>
      <p><%#= link_to "注文履歴一覧を見る", orders_path, class: "btn btn-primary" %></p>
    </div>
  </div>
</div>