config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :games, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
    # resources :jenres, only: [:index, :create, :edit, :update]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    # get '/about' => 'homes#about',as: 'about'
    # resources :games, only: [:new, :create]
    get 'games/search' => "games#search"
    resources :games, only: %i[show], params: :item_code
    # get 'games' => 'games#index'
    get 'games/:id' => 'games#show',as: 'games/show'



    get 'current_customer/show' => 'customers#show'
    get 'current_customer/information/edit' => 'customers#edit'
    patch 'current_customer/show' => "customers#update"
    put 'current_customer/show' => "customers#update"
    get 'current_customer/unsubscribe' => 'customers#unsubscribe',as: 'unsubscribe'
    patch 'current_customer/withdrawal' => 'customers#withdrawal',as: 'withdrawal'

    # get 'posts/new' => 'posts#new'
    # post 'posts' => 'posts#create'
    # get 'posts' => 'posts#index'
    # get 'posts/:id' => 'posts#show',as: 'posts/show'
    get "search" => "posts#search"

    resources :posts, only: [:new, :create, :index, :show, :edit, :update] do
      resources :comments, only: [:create]
    end



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_post_and_tag.rb
class AssociationPostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :customer

  validates :comment_content, presence: true
end

app/models/comment_notification.rb
class CommentNotification < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :date_of_birth, presence: true


  def self.guest_sign_in
    pp '--------------------------'
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "ユーザー"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
      user.nickname = "ゲストユーザー"
      user.date_of_birth = "2023/08/05"
      user.gender = 2

    end
  end

  enum gender: { man: 0, woman: 1, guest: 2 }

end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/follow_notification.rb
class FollowNotification < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  # belongs_to :jenre, optional: true
  has_many :posts, dependent: :destroy
end

app/models/jenre.rb
class Jenre < ApplicationRecord
  has_many :game, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :game
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags


  validates :body, presence: true
  validates :star, presence: true

  # scope :published, -> {where(is_published_flag: true)}
  # scope :unpublished, -> {where(is_published_flag: false)}

  enum status: { public: 0, private: 1 }, _prefix: true

  def self.search(keyword)
    where("facility_name LIKE ? or address LIKE ? or detailed_description LIKE ?", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%")
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :association_post_and_tags, dependent: :destroy
  has_many :posts, through: :association_post_and_tags

  validates :tag_type, presence: true
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(10)

  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to admin_games_path(@game)
  end

  def show
    @game = Game.find(params[:id])
    
    
    #@post = Post.find(params[:id])
    #@comments = @post.comments
    #@posts = Post.all
    @posts = @game.posts
    
    #@customers = Customer.all
  end

  def edit
    @games = Game.find(params[:id])
  end

  def update
    @games = Game.find(params[:id])
    @games.update(game_params)
    redirect_to admin_game_path(@games.id)

  end

  private

  def game_params
    params.require(:game).permit(:name, :introduction, :release_date, :image)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tag = Tag.new
    @tags = Tag.page(params[:page])
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "新しいタグを追加しました。"
    else
      @tags = Tag.page(params[:page])
      flash.now[:alert] = "タグの追加に失敗しました。"
      render :index
    end
  end


  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの更新に成功しました。"
    else
      flash.now[:alert] = "タグの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_type, tag_ids: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/jenres_helper.rb
module Admin::JenresHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/games/edit.html.erb
<h1>Admin::Games#edit</h1>
<p>Find me in app/views/admin/games/edit.html.erb</p>

app/views/admin/games/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-12">
      <div class="row mb-4 ">
        <div class="col d-flex justify-content-between">
          <div>
            <h5>ゲーム一覧</h5>
          </div>
          <div>
            <%= link_to new_admin_game_path do %>
              <i class="fas fa-plus-circle fa-2x"></i>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>ゲームID</th>
                <th>ゲーム名</th>
                <th>発売日</th>
                <!--<th>ジャンル</th>-->
                <!--<th>ステータス</th>-->
              </tr>
            </thead>

            <tbody>
              <% @games.each do |game| %>
                <tr>
                  <th><%= game.id %></th>
                  <th><%= link_to game.title, admin_game_path(game) %></th>
                  <th><%= game.sales_date %></th>
                  <!--<th></th>-->
                  <!--<th></th>-->
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
      <div class="d-flex justify-content-center">
        <%= paginate @games %>
      </div>
    </div>
  </div>
</div>

app/views/admin/games/new.html.erb
<div class="container">
  <h1>ゲーム新規登録</h1>
  <div class="row">

  </div>

  <div class="row">
    <div class="col d-flex justify-content-center">
      <%= form_with model: @game, url: admin_games_path do |f| %>
        <div class="row">
          <div class="col-4">
            <p>ゲーム画像</p>
          </div>
          <div class="col-8">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p>ゲーム名</p>
          </div>
          <div class="col-8">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p>ゲーム説明</p>
          </div>
          <div class="col-8">
            <%= f.text_area :introduction %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p>発売日</p>
          </div>
          <div class="col-8">
            <%= f.text_field :release_date %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <!--<p>販売ステータス</p>-->
          </div>
        </div>

        <div class="row d-flex justify-content-center mt-5">
          <%= f.submit '新規登録', class: "btn btn-success pl-4 pr-4" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/games/show.html.erb
<!--<h1>Admin::Games#show</h1>-->
<!--<p>Find me in app/views/admin/games/show.html.erb</p>-->

<div class="container">
  <h2 class="pb-3">ゲーム詳細</h2>

  <div class="row">
    <div class="col-10">
      <div class="row">
        <div class="col-3">
          <p>ゲームタイトル</p>
        </div>
        <div class="col-9">
          <%= @game.title %>
        </div>
      </div>

      <!--<div class="row">-->
      <!--  <div class="col-2">-->
      <!--    <p>発売元名</p>-->
      <!--  </div>-->
      <!--  <div class="col-10">-->
      <!--    <%#= @post.game.label %>-->
      <!--  </div>-->
      <!--</div>-->

      <div class="row pt-4">
        <div class="col-3">
          <p>対応機種</p>
        </div>
        <div class="col-9">
          <%= @game.hardware %>
        </div>
      </div>

      <div class="row pt-4">
        <div class="col-3">
          <p>発売日</p>
        </div>
        <div class="col-9">
          <%= @game.sales_date %>
        </div>
      </div>
    </div>

    <!--<div class="col-2"></div>-->

    <div class="col-2">
      <%= image_tag(@game.image_url + "?_ex=200x200") %>
    </div>
  </div>

  <h5 class="pt-5 pb-3">レビュー内容</h5>
  <table class="table">
    <tbody>
    <% @posts.each do |post| %>
      <tr class="d-flex">
        <td class="p-2 flex-grow-1"><div><%= post.body %></div></td>

        <td>
          <div id="star-rate<%= post.id %>"></div>
          
        
          <script>
            $('#star-rate<%= post.id %>').empty();
            var elem<%= post.id %> = document.querySelector('#star-rate<%= post.id %>');
            var opt<%= post.id %> = {
              size:    36,
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
             half:      false,
              score: <%= post.star %>,
              readOnly: true
            };
            raty(elem<%= post.id %>, opt<%= post.id %>);
          </script>
        </td>
        <td><%= link_to "詳細", admin_post_path(id: post.id, game_id: post.game_id) %></td>
      </tr>
      
      
    <% end %>
    </tbody>
  </table>

app/views/admin/tags/edit.html.erb
<div class="container border border-white contents-area bg-white" >
  <div class="row mt-4 md-2">
    <div class="col-md-6 mx-auto">

      <%#= render "error", tag: @tag %>
      <h3><strong><%= flash[:alert] %></strong></h3>
      <h3><strong class="border-bottom border-dark">タグ編集</strong></h3>

        <%= form_with model: @tag, url:admin_tag_path,method: :patch do |f| %>
          <table class="table table-borderless mt-3">
            <tbody>
              <tr>
                <td class="align-middle">
                  <label for="genre_name">タグ名</label>
                </td>
                <td class="align-middle">
                  <%= f.text_field:tag_type %>
                </td>
                <td>
                  <%= f.submit "変更を保存",class: "btn btn-success",  method: :patch, "data-confirm" => "このタグを変更した場合、投稿者のタグも同時に変更されます。本当に変更してよろしいですか?"  %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>

    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container border border-white contents-area bg-white" >
  <div class="row mt-5 mb-5">
    <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12 mx-auto">

      <%#= render "error", tag: @tag %>
      <!--<h3><strong><%#= flash[:notice] %><%#= flash[:alert] %></strong></h3>-->
      <h3 class="text-center"><strong class="border-bottom border-dark">タグ一覧・追加/削除</strong></h3>

        <%= form_with model: @tag, url: admin_tags_path,method: :post do |f| %>
          <table class="table table-border contents-area mt-5">
            <tbody>
              <tr>
                <td class="align-middle">タグ名</td>
                <td class="center align-middle">
                  <%= f.text_field:tag_type,:size=>"35" %>
                </td>
                <td colspan="2"></td>
                <td>
                  <%= f.submit "新規登録", class: "btn btn-primary btn-lg" %>
                </td>
              </tr>
        <% end %>
          <thead class="table-active">
            <tr>
              <th>タグ</th>
              <th colspan="6"></th>
            </tr>
          </thead>
            <tbody>
              <% @tags.each do |tag| %>
                <tr>
                  <td class="align-middle"><%= tag.tag_type %></td>
                  <td colspan="3"></td>
                  <td>
                    <%= link_to "タグを変更する", edit_admin_tag_path(tag.id), class: "btn btn-success" %>
                    <%= link_to "タグを削除する", admin_tag_path(tag.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当にタグを削除しますか?" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <div class="pagination justify-content-center mt-3">
            <%#= paginate @tags, theme: "bootstrap-5" %>
          </div>

    </div>
  </div>
</div>