config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#new_guest'
  end

  namespace :admin do
    root to: 'homes#top'
    resources :games, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only: [:show, :destroy] do
      resources :comments, only: [:destroy]
    end
    # resources :jenres, only: [:index, :create, :edit, :update]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    # get '/about' => 'homes#about',as: 'about'
    # resources :games, only: [:new, :create]
    get 'games/search' => "games#search"
    resources :games, only: %i[show], params: :item_code
    # get 'games' => 'games#index'
    get 'games/:id' => 'games#show',as: 'games/show'



    get 'current_customer/show' => 'customers#show'
    get 'current_customer/information/edit' => 'customers#edit'
    patch 'current_customer/show' => "customers#update"
    put 'current_customer/show' => "customers#update"
    get 'current_customer/unsubscribe' => 'customers#unsubscribe',as: 'unsubscribe'
    patch 'current_customer/withdrawal' => 'customers#withdrawal',as: 'withdrawal'

    # get 'posts/new' => 'posts#new'
    # post 'posts' => 'posts#create'
    # get 'posts' => 'posts#index'
    # get 'posts/:id' => 'posts#show',as: 'posts/show'
    get "search" => "posts#search"

    resources :posts, only: [:new, :create, :index, :show, :edit, :update] do
      resources :comments, only: [:create]
    end



  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_post_and_tag.rb
class AssociationPostAndTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :customer

  validates :comment_content, presence: true
end

app/models/comment_notification.rb
class CommentNotification < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :date_of_birth, presence: true


  def self.guest_sign_in
    pp '--------------------------'
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "ゲスト"
      user.first_name = "ユーザー"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ユーザー"
      user.nickname = "ゲストユーザー"
      user.date_of_birth = "2023/08/05"
      user.gender = 2

    end
  end

  enum gender: { man: 0, woman: 1, guest: 2 }

end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/follow_notification.rb
class FollowNotification < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image
  # belongs_to :jenre, optional: true
  has_many :posts, dependent: :destroy
end

app/models/jenre.rb
class Jenre < ApplicationRecord
  has_many :game, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :game
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags


  validates :body, presence: true
  validates :star, presence: true

  # scope :published, -> {where(is_published_flag: true)}
  # scope :unpublished, -> {where(is_published_flag: false)}

  enum status: { public: 0, private: 1 }, _prefix: true

  def self.search(keyword)
    where("facility_name LIKE ? or address LIKE ? or detailed_description LIKE ?", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%")
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :association_post_and_tags, dependent: :destroy
  has_many :posts, through: :association_post_and_tags

  validates :tag_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/jenres_helper.rb
module Admin::JenresHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom border-primary mb-5 pb-3">
      <div class="container ">
        <nav class="navbar navbar-bottom">
          <div class="d-flex align-items-center">
            <h1 class="pl-3 pr-3 border border-dark mt-5">game_review</h1>
          </div>

          <ul class="navbar-nav ml-auto">
            <form class="form-inline">
              <% if admin_signed_in? %>
                <% if request.fullpath.include? "/admin" %>
                  <li class="nav-item ml-5">
                    <%= link_to "ゲーム一覧",admin_games_path, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                  <li class="nav-item ml-5">
                    <%= link_to "会員一覧", admin_customers_path, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                  <li class="nav-item ml-5">
                    <%= link_to "レビュー履歴一覧", admin_root_path, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                  <!--<li class="nav-item ml-5">-->
                  <!--  <%#= link_to "ジャンル一覧", admin_jenres_path, class: "btn btn-sm btn-outline-secondary" %>-->
                  <!--</li>-->
                  <li class="nav-item ml-5">
                    <%= link_to "タグ一覧", admin_tags_path, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                  <li class="nav-item ml-5">
                    <%= link_to "ろぐあうと", destroy_admin_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                <% else %>
                  <li class="nav-item ml-5">
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
                  </li>
                <% end %>
              <% elsif customer_signed_in? %>
                <div class="d-flex">
                  <p>ようこそ、<br><%= current_customer.nickname %>さん！</p>
                </div>
                <li class="nav-item ml-5">
                  <%= link_to "マイページ", current_customer_show_path(current_customer.id), class: "btn btn-sm btn-outline-secondary" %>
                </li>
                <!--<li class="nav-item ml-5">-->
                <!--  <%#= link_to "ゲーム一覧", games_path, class: "btn btn-sm btn-outline-secondary" %>-->
                <!--</li>-->
                <li class="nav-item ml-5">
                  <%= link_to "投稿一覧", posts_path, class: "btn btn-sm btn-outline-secondary" %>
                </li>
                <li class="nav-item ml-5">
                  <%=  link_to "ゲームを検索",games_search_path,class: ' btn btn-sm btn-outline-secondary ' %>
                </li>
                <!--<li class="nav-item ml-5">-->
                <!--  <%#=  link_to "投稿", new_game_path,class: ' btn btn-sm btn-outline-secondary ' %>-->
                <!--</li>-->
                <li class="nav-item ml-5">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: "btn btn-sm btn-outline-secondary" %>
                </li>
              <% else %>
                <!--<li class="nav-item ml-5">-->
                <!--  <%#= link_to "About", about_path, class: "btn btn-sm btn-outline-secondary" %>-->
                <!--</li>-->
                <!--<li class="nav-item ml-5">-->
                <!--  <%#= link_to "ゲーム一覧", games_path, class: "btn btn-sm btn-outline-secondary" %>-->
                <!--</li>-->
                <li class="nav-item ml-5">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-sm btn-outline-secondary" %>
                </li>
                <li class="nav-item ml-5">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-sm btn-outline-secondary" %>
                </li>
                <li class="nav-item ml-5">
                  <%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, method: :post, class: "login btn btn-sm btn-outline-secondary" %>
                </li>
              <% end %>
            </form>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer class="mt-5 pt-5 border-top border-primary ">
      <div class="d-flex justify-content-center">
        <p class="pr-3">Copyright © All Rights Reserved by For What?</p>
        <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
        <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_31130.gif" border="0" alt="Rakuten Web Service Center" title="Rakuten Web Service Center" width="311" height="30"/></a>
        <!-- Rakuten Web Services Attribution Snippet TO HERE -->
      </div>
    </footer>

  </body>
</html>